Add aliases for bookmarks
lalitmee/browse.nvim pull request #12
Opened 2022-12-05 23:18 UTC by Quminouse

May help with #4

2022-12-08 05:52 UTC, lalitmee commented
@Quminouse, thanks for the PR.

I think its better if we support both the things together, like this:
```lua
local bookmarks = {
    ["browse.nvim"] = "https://github.com/lalitmee/browse.nvim",
    ["cobalt2.nvim"] = "https://github.com/lalitmee/cobalt2.nvim",
    ["dNotes"] = "https://github.com/lalitmee/dNotes",
    ["dotfiles"] = "https://github.com/lalitmee/dotfiles",
}
```
The `bookmarks` can be declared as the above, so that we don't have to maintain two things `bookmarks` and `aliases`.

What do you think about this?

2022-12-09 22:23 UTC, Quminouse commented
I've implemented something like this that should work for both bookmarks and aliases:
```lua
local bookmarks = {
  -- Folders can be defined like so:
  ["folder"] = { "https://github.com/", 
                 "https://github.com/lalitmee",  }
  -- URLs can be aliased like so:
  ["google"] = "https://www.google.com/"
  -- Regular bookmarks should work as well:
  "https://www.bing.com/"
  -- A combination of any of the above should work as well:
  ["github"] = { ["github"] = "https://github.com/",
                 ["lalitmee"] = { ["browse.nvim"] = "https://github.com/lalitmee/browse.nvim",
                                  ["cobalt2.nvim"] = "https://github.com/lalitmee/cobalt2.nvim", }, }
}
```
Let me know if you have any suggestions but I think this is pretty good. 
Did you want me to add that to one of my existing pull requests or open a new one?
Thank you for the feedback!

2022-12-10 13:00 UTC, lalitmee requested changes

2022-12-10 13:00 UTC, lalitmee commented on README.md
> +  require("browse").browse({ bookmarks = bookmarks, aliases = aliases})
I don't think that now we need an extra variable `aliases` because we can do `aliases` in the `bookmarks`. So can you please refactor it.

2022-12-10 13:00 UTC, lalitmee commented on README.md
> +}
Just put this in a lua file and format it properly. It a little bit of confusing and not properly readable.

2022-12-10 13:00 UTC, lalitmee commented on lua/browse/bookmarks.lua
> +  local aliases = config["aliases"] or {}
We don't need `aliases` as an explicit variable, as we can add these too in the `bookmarks`.

2022-12-10 15:20 UTC, Quminouse commented on README.md
> +}
I added a file 'example_bookmarks.lua' that should be better formatted. I could add variables to make it more readable if you would like but I think it is much clearer now.

2022-12-11 17:09 UTC, closed without merging