Fix browse on windows, refactor code, add safety and features
lalitmee/browse.nvim pull request #8
Opened 2022-08-06 15:53 UTC by B4mbus

This PR:
 - fixes browse on windows (it actually works now).
 - enables users to type spaces and special characters in queries (due to URL escaping).
 - brings a little bit refactoring to the code.
 - fixes a few minor issues (where config is nil).

2022-08-06 19:06 UTC, lalitmee requested changes
Hey @B4mbus, first of all, thanks for your contribution and sorry for not mentioning some of the things which should have been there as a `contributing` guide.

There are some things which if you can do, it would be very easy to follow some standards. Such as:
1. Please use `spaces` instead of `tabs` for `indentation`.
2. Why are we renaming `util` to `browser`? I think there are already so many terms related to `browser`, that's why I was also thinking of doing something for the `browse` function which the plugin exposes. Please elaborate if you have something specific in your mind.
3. I saw that you have written some more helper functions in `browser.lua` and you have also added some comments for those.

Again, thanks for your contribution. I really appreciate your help in improving the plugin.

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/bookmarks.lua
> +local browser = require("browse.browser")
Why rename it? I thought `util` was like the **utilities** which were needed for some things.

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/bookmarks.lua
> +				browser.plain_search(selection[1])
use `spaces` instead of `tabs`

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/browser.lua
> +local M = {}
This file is a mix of `spaces` and `tabs`. Can we please fix that?

And, can you please also mention your thinking of changing this file from `util` to `browser`?

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/init.lua
> +	local config = config or {}
This file is also mix of `spaces` and `tabs`. Please fix this too.

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/browser.lua
> +local start_browser_for = function(target)
Can we please rename this function to `open_browser`?

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/browser.lua
> +local escape_target = function(target)
Since this function works as a tool for all the other functions which are being used in `browse`, please move this function before the `start_browser_for` function.

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/browser.lua
> +M.plain_search = function(input)
I do not understand the meaning of `plain_search` here. I think we will have to think of a more meaningful name for this. Can you think of something else?

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/browser.lua
> +		local sane_input = escape_target(vim.fn.trim(input))
Can we rename the `sane_input` to `escaped_input`

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/browser.lua
> +M.generic_search = function(target_fn)
What do you think of renaming this to just `search`?

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/browser.lua
> +M.generic_search_custom = function(custom_fn)
For this, what do you think of renaming this to `custom_search`?

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/browser.lua
> +M.generic_search_for = function(format)
Can you think of some other name for this too?

2022-08-06 19:06 UTC, lalitmee commented on lua/browse/input.lua
> +local browser = require("browse.browser")
mix of `spaces` and `tabs`

2022-08-06 19:19 UTC, B4mbus commented
@lalitmee 
> Why rename it? I thought `util` was like the **utilities** which were needed for some things.

The module is no longer focused on providing general utilities, now it's specialized and the only functionality it provides is opening the browser and a search engine.

> use `spaces` instead of `tabs`

Alright. Do I use 2 or 4 indentation level?

> Can we please rename this function to `open_browser`?

Sure.

> Can we rename the `sane_input` to `escaped_input`

Sure.

> Since this function works as a tool for all the other functions which are being used in browse, please move this function before the `start_browser_for` function.

Sure.

> I do not understand the meaning of `plain_search` here. I think we will have to think of a more meaningful name for this. Can you think of something else?

Hmm.. All the other searching functions do something (format or accept a callable), I thought `plain_search` would be a good name but I can't think of anything else. Maybe leave it or change to`default_search` and rename the other to `format_search` and `callback_search`?

> What do you think of renaming this to just `search`?
> 
> For this, what do you think of renaming this to `custom_search`?
> 
> Can you think of some other name for this too?

The `generic_` prefix can be omitted, sure, yeah. Tho now I'm thinking about the convention mentioned earlier - 
`generic_custom_search` -> `callback_search` or `custom_search`
`generic_search` -> `search` or `format_search`
`plain_search` -> `default_search` or `plain_search`

We can also do
`generic_custom_search` -> `callback_search` or `custom_search`
`generic_search` -> `format_search`
`plain_search` -> `search`

2022-08-07 04:19 UTC, lalitmee commented
@B4mbus,
> The module is no longer focused on providing general utilities, now it's specialized and the only functionality it provides is opening the browser and a search engine.

But as we know that the plugin is about browsing, it means the `utils` file will provide some `utils` for the browsing. Do you agree?

> Alright. Do I use 2 or 4 indentation level?

2 spaces

> `generic_custom_search` -> `callback_search`
`generic_search` -> `search`
`plain_search` -> `default_search`

We can do this.

2022-08-07 07:59 UTC, B4mbus commented
@lalitmee well, yes, the plugin is about browsing, but it's split into several modules, every and each doing one concrete thing, I'd personally argue that `utils` should be named along the lines of `browser`, `searcher` or `engine`, but alright, I'll change it to `utils` again.

2022-08-07 08:21 UTC, B4mbus commented
I did everything you wanted me to. I also changed `generic_search_for` into `format_search`, because we haven't discussed that. What do you think? Do I change it to something else?

2022-08-07 11:23 UTC, lalitmee approved these changes

2022-08-07 11:23 UTC, merged